apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secretstore
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: poetic-archive-455316-b4
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-key
            key: secret-access-credentials
            namespace: external-secrets
