apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-key
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretstore
    kind: ClusterSecretStore
  target:
    name: web-app-secret   # resulting K8s Secret name
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: API_KEY  # name of the GCP Secret Manager secret
