name: "web-app"
image:
  repository: eranzaksh/leumi
  tag: ""
service:
  type: ClusterIP
  targetPort: 5000
  port: 443
spec:
  replicaCount: 1

argocd:
  namespace: argocd
  ingress:
    enabled: true
    host: eranargocd.duckdns.org
    className: nginx
