apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- with .Values.argocd.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.argocd.ingress.className | default "nginx" }}
  tls:
  - hosts:
    - {{ .Values.argocd.ingress.host }}
    secretName: "{{ .Values.argocd.namespace }}-tls"
  rules:
    - host: {{ .Values.argocd.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443